### ISSUE TITLE
[FEATURE REQUEST] Add vote streaks to both factions and survival

### ISSUE THREAD

**Issue by vinceingithub** [LeftyIsHere/GoldenWaters#12]
**Describe the addition**
After certain voting milestones (5 days, 15 days, 30 days **in a row, not total**) you'd get rewards of cash and keys.

**Why do you want this feature?**
Further incentivizes voting

**Additional context**
my head doesn't hurt rn :D

**Comment by LeftyIsHere** [comment]
I will look into doing this in a couple weeks.

**Comment by LeftyIsHere** [comment]
Denied for the time being until I find a way to set up voting as it is now with no bugs
