### ISSUE TITLE
[FEATURE REQUEST] Make moving /homes easier

### ISSUE THREAD

**Issue by vinceingithub** [LeftyIsHere/GoldenWaters#15]
**Describe the addition**
Right now, when you try to set a home with the same name as an old home it gives you an error. Please make it so when you try to set a home with the same name as another home it deletes the old home of the same name and creates a new one at the new location.

**Why do you want this feature?**
It makes moving homes easier.

**Additional context**
my head hurt again yesterday :(

**Comment by LeftyIsHere** [comment]
I think its better to be sure that you dont accidentally delete a home without knowing. Its just one extra command vs 10 commands to find where the home used to be
