### ISSUE TITLE
[FEATURE REQUEST] List of Important Warps / Command

### ISSUE THREAD

**Issue by sirbean1** [LeftyIsHere/GoldenWaters#17]
**Describe the addition**
Add a command on the Minecraft server and message in the Discord server (either pinned in #survival or in #faq) that lists important or major warps. These could include admin warps or massive towns. It could also be a perk for ranked users (1 free major warp?)

**Why do you want this feature?**
It can help people find important warps, admin warps, and more.

**Comment by vinceingithub** [comment]
The faq section for this will be created as a part of #16

**Comment by vinceingithub** [comment]
If anyone would like to help out with this just please make a list of all admin warps on the survival server (i.e. PVP, PVP+, etc) and comment it on this post.

**Comment by sirbean1** [comment]
**Alphabetical Order**
/warp chestshops
/warp crates
/warp parkour
/warp pvp
/warp pvp+
/warp shop
/warp spawn
/warp sumo

There may be more, but that's the ones I can think of (can't get online, big sad.)

**Comment by vinceingithub** [comment]
Dyno command added, in-game equal to be done

**Comment by LeftyIsHere** [comment]
done :)
