### ISSUE TITLE
[FEATURE REQUEST] PartyChat Plugin

### ISSUE THREAD

**Issue by sirbean1** [LeftyIsHere/GoldenWaters#18]
**Describe the addition**
There's a plugin that allows users to talk in a separate chat than other users, similar to /whisper, though multiple users can use it at the same time. More info on the SpigotMC page.

**Why do you want this feature?**
It can help with communication between town members, groups of friends, or people working together.

**Additional context**
This was suggested originally by Dabsahoy#5432
Plugin Link: https://www.spigotmc.org/resources/partychat.79295/

**Comment by LeftyIsHere** [comment]
I will add this when I have time

**Comment by bwmp** [comment]
Added, should be implemented next restart
