### ISSUE TITLE
[FEATURE REQUEST] Add ChatItems

### ISSUE THREAD

**Issue by starve-l** [LeftyIsHere/GoldenWaters#19]
**Describe the addition**
The ChatItems Plugin lets you send your items in chat with the enchants etc just like when you hover over them
**Why do you want this feature?**
Its a great way to trade items/advertise shops/flex

**Additional context**
https://www.spigotmc.org/resources/chatitems-now-with-1-8-support.81179/

**Comment by LeftyIsHere** [comment]
I dont feel like this is necessary considering we already have /ah
