### ISSUE TITLE
[FEATURE REQUEST] Update the spawn shop to be larger, improved, and have more items

### ISSUE THREAD

**Issue by sirbean1** [LeftyIsHere/GoldenWaters#20]
**Describe the addition**
At spawn, expand the shop to have it's own room and much more items. Here's a list of some item additions:

 - Emeralds
 - More Food
 - Nether Stars?
 - Shulker Shells or Boxes
 - Gold
 - More blocks
 - Hermitcraft-Barge Items (items that are annoying to craft)

If you think adding this much might be overpowered, you can always just super overprice it so that there's less encouragement to use the shop but it's still there in case you're desperate. 

**Why do you want this feature?**
Finding the right shop, cheap shops, stocked shops, or shops with the items you need can be difficult, and spawn shop is fairly useful to have at your disposal in case you need an item you can't find or is not stocked.

**Additional context**
I need 13 votes until I can apply for Detective.

Also I hope vince's head is feeling better.

**Comment by LeftyIsHere** [comment]
This will not be done because the survival economy is meant to be lead by the players, increasing items sold in the server shop will discourage that.
