### ISSUE TITLE
[BUG] Spam clicking "Next Page" in coreprotect logs causes you to get kicked for spamming

### ISSUE THREAD

**Issue by vinceingithub** [LeftyIsHere/GoldenWaters#24]
**Describe the bug**
Self-explanatory

**To Fix**
One possible fix for this is to remove the spam auto-kick for staff members

**Comment by kakduman** [comment]
Let me know if you figure this out. I don't believe there's a way to turn it off without /op.

**Comment by kakduman** [comment]
You can however add `/co` to `spam-exclusions` in spigot.yml.  Thanks billy from purpur for that idea :)

**Comment by vinceingithub** [comment]
@Pemigrade Thanks for this comment, I somehow missed this but I just saw it now. Very helpful!

**Comment by vinceingithub** [comment]
Fixed. Restart Required.
