### ISSUE TITLE
[FEATURE REQUEST] Set up bungee staff chat

### ISSUE THREAD

**Issue by vinceingithub** [LeftyIsHere/GoldenWaters#27]
**Describe the addition**
<!Describe what you want to happen.>
Set up a bungee staff chat so that staff chats on factions are visible in surv and vice versa, also have them all sent in #staff but maybe have them be tagged like [Survival][Mod] Name > message
**Additional context**
<!Add any other context or screenshots about the feature request here..>
Needs to be done by Lefty.

**Comment by GuydsMaidDress** [comment]
is it possible to make it so we can toggle the messages we see?
so for example something like, /staffchat survival
or like
/staffchat all
or something like that

**Comment by LeftyIsHere** [comment]
Not sure tbh, I know this is something that can be done though and will look into it.

**Comment by LeftyIsHere** [comment]
I can add this but it wont link to discord so there will be two staff chats. I will do this this weekend if not too busy with other things.

**Comment by bwmp** [comment]
lefty hurry up

**Comment by vinceingithub** [comment]
mas rapido

**Comment by vinceingithub** [comment]
Done, Implemented
