### ISSUE TITLE
[FEATURE REQUEST] Set up silk touch spawners in Factions

### ISSUE THREAD

**Issue by vinceingithub** [LeftyIsHere/GoldenWaters#29]
**Describe the addition**
<!Describe what you want to happen.>
Self explanatory
**Additional context**
<!Add any other context or screenshots about the feature request here..>
make sure you assign ``silkyspawners.mine`` to the group ``default``/``guest`` in context factions tho
Plugin: https://www.spigotmc.org/resources/silky-spawners-lite-silk-touch-your-spawners-silk-spawners-1-16-4-support.76103/

**Comment by LeftyIsHere** [comment]
plugin has been added and enabled :)
