### ISSUE TITLE
[TO DO] Set up the Survival Portal in the Factions spawn

### ISSUE THREAD

**Issue by vinceingithub** [LeftyIsHere/GoldenWaters#32]
**Describe the addition**
<!Describe what you want to happen.>
self explanatory

**Comment by vinceingithub** [comment]
Is there a reason this is being put off? I thought the plugin worked now.

**Comment by LeftyIsHere** [comment]
Survival doesnt have a factions portal and creative wont either so im probably going to repurpose that area of spawn instead of putting the portal there.
