### ISSUE TITLE
[FEATURE REQUEST] Give Immortals the permission to use magic codes when renaming items with SimpleRename

### ISSUE THREAD

**Issue by starve-l** [LeftyIsHere/GoldenWaters#37]
**Describe the addition**
Give Immortals the permission to use magic codes when renaming items with SimpleRename

**Why do you want this feature?**
I'm making a casino and I need some kind of token. If I would use a normal name, other people could copy the item really easy. However a name with magic letters (`&k`) would make it way harder to copy the item.

**Additional context**
![image](https://user-images.githubusercontent.com/68667474/104938672-abb75600-59af-11eb-96b0-dfdb4edc688b.png)

**Comment by vinceingithub** [comment]
This could get spammy but eh

**Comment by LeftyIsHere** [comment]
Would make chat look messy. May be reconsidered in the future
