### ISSUE TITLE
[FEATURE REQUEST] Give everyone permissions to do /eglow visibility none

### ISSUE THREAD

**Issue by starve-l** [LeftyIsHere/GoldenWaters#38]
**Describe the addition**
Give everyone permissions to do `/eglow visibility none`

**Additional context**
The glowing effect can lag out a lot of pcs, in fact my FPS drop to 10-20. Please consider adding this feature as it makes the server more enjoyable.

**Comment by LeftyIsHere** [comment]
Done :)
