### ISSUE TITLE
[FEATURE REQUEST] Switch the emojis for the "Server has started/stopped" messages

### ISSUE THREAD

**Issue by vinceingithub** [LeftyIsHere/GoldenWaters#4]
**Describe the addition**
Describe what you want to happen.
Switch the emojis in the server status messages from the default ones to our custom Yes/No reaction ones.

**Why do you want this feature?**
Explain why this feature should be added.
It would be cool and quirky

**Additional context**
my head hurts

**Comment by LeftyIsHere** [comment]
Done
