### ISSUE TITLE
[FEATURE REQUEST] Change gamemodes in creative, give players the permission to clear/reset/merge their own plot.

### ISSUE THREAD

**Issue by starve-l** [LeftyIsHere/GoldenWaters#6]
**Describe the addition**
Change gamemodes in creative, give players the permission to clear/reset/merge their own plot.

**Why do you want this feature?**
It makes the creative server more enjoyable.

**Additional context**
I think the needed permissions are `plots.delete`, `plots.merge` and `plots.clear`, not sure though.

**Comment by LeftyIsHere** [comment]
I will look into doing this in a couple weeks.

**Comment by sirbean1** [comment]
This good :)

**Comment by LeftyIsHere** [comment]
I dont plan on working on the creative world any more but when the creative server opens (1-2 weeks) these features will be included.
