### ISSUE TITLE
[FEATURE REQUEST] Sync ingame mutes with discord

### ISSUE THREAD

**Issue by vinceingithub** [LeftyIsHere/GoldenWaters#7]
**Describe the addition**
Describe what you want to happen.
If you are muted in game you should get the @muted role on the discord for the duration of your mute

**Why do you want this feature?**
Explain why this feature should be added.
This should be added so that people can't mute evade in #global

**Additional context**
my head still hurts, different reason this time :(

**Comment by LeftyIsHere** [comment]
I have added it and it _should_ work after the next restart. This will be fully set up in about a day.

**Comment by LeftyIsHere** [comment]
Done. Muted role has been deleted since we use litebans mutes instead of essentials mutes. Any messages sent in #global by a muted player are deleted in the discord and cancelled in game.
