### ISSUE TITLE
[FEATURE REQUEST] Make a tournament feature

### ISSUE THREAD

**Issue by QUIDD60x** [LeftyIsHere/GoldenWaters#9]
**Describe the addition**
There should be a tournament feature in which every few weeks (or when a bunch of people want it) in which people can pay a little bit (~100) to participate in building, PVP, fun games, challenges, etc. And the winner gets to keep the money/Other special prizes.
**Why do you want this feature?**
This would be a fresh take to everyone's time so they wouldn't get bored/leave the server so easily, it's unique as heck so people might come just for that, it gets everyone to know each other, its nice content for creators like me and Cacko, it would be easier to weave out hackers, and I really wanna lose so maybe if money was on the line people would try harder.

**Additional context**
I don't think you understand how much I want to lose. I won a 1v3 with a piece of steak. I fight a hacker and I still win. (Sure yeah he didn't hack on me but still) I really like challenges but this is too much

**Comment by LeftyIsHere** [comment]
I don't plan to invest too much more time into pvp+ as golden waters is a survival server, so it'd be better to focus on that aspect more. There is no way to automate tournaments without completely reworking the pvp+ system so I think i will leave tournaments for players to organize. I may still host tournaments at pvp+ occasionally though that are free to enter.
